#!/bin/bash
#PBS -l walltime=02:30:00
#PBS -l nodes=1:ppn=8
#PBS -l mem=8000mb
#PBS -j oe
#PBS -q copperhead

cd $PBS_O_WORKDIR

module load node.js/4.4.0

echo unzipping ${SRR} files
gunzip "downloadSraFastq/"${SRR}*

echo "got SRR ${SRR}"

echo "running 100"
node fastqParserSampler.js "downloadSraFastq/"${SRR}".fastq" 100

echo "running 500"
node fastqParserSampler.js "downloadSraFastq/"${SRR}".fastq" 500

echo "running 1000"
node fastqParserSampler.js "downloadSraFastq/"${SRR}".fastq" 1000

echo "running 2000"
node fastqParserSampler.js "downloadSraFastq/"${SRR}".fastq" 2000

echo "running 5000"
node fastqParserSampler.js "downloadSraFastq/"${SRR}".fastq" 5000

echo "running 10000"
node fastqParserSampler.js "downloadSraFastq/"${SRR}".fastq" 10000

echo "running 50000"
node fastqParserSampler.js "downloadSraFastq/"${SRR}".fastq" 50000

echo "running 100000"
node fastqParserSampler.js "downloadSraFastq/"${SRR}".fastq" 50000

echo " ... gzip ... "
#gzip ${SRR}*